# https://stackoverflow.com/a/70818366/7981413
inherit_mode:
  merge:
    - Exclude

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
  Safe: true
  SafeAutoCorrect: true

Style/NumericPredicate:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always
  Safe: true
  SafeAutoCorrect: true

Style/EmptyMethod:
  Safe: true
  SafeAutoCorrect: true
